version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s" 

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: /var/log/mnemosyneos/app.log
    maxBytes: 10485760   # 10 MB
    backupCount: 5

loggers:
  root:
    level: INFO
    handlers: [console, file]
  mnemosyneos:
    level: INFO
    handlers: [console, file]
    propagate: no

# Optionally, you can define environment-specific logger levels via separate YAML files or by programmatically overriding below.
